### ISSUE TITLE
.on logic executes twice

### ISSUE THREAD

**Issue by mishoboss** [eddyystop/feathers-reduxify-services#1]
Hello and congrats about this great module. Maybe I don't quite understand it, but this snippet logs twice 'PAGE CREATED' when a new page record is created. Is this normal? If yes, why?

```
feathersApp.service('pages').on('created', data => { getStore().dispatch(
       services.pages.on('created', data, (event, data, dispatch, getState) => {
         console.log('PAGE CREATED', data)
       })
   ); 
});
```

And one question - is there a mechanism to keep in sync data in redux store with the feathers services? Whenever some client modifies some data, all connected clients to update its own redux store (without requesting the whole data again)? If there isn't such built-in functionality, do you plan it in future? And how to achieve it now best?

Thank you

**Comment by eddyystop** [comment]
Hello, and thanks.

(1) I uncommented the `messages.on` code in example/client/feathers/index.js:15-25. Its functionally identical to your code above.

The example logs only once when a message is added. One message is logged in the 'initialization' code on line 11 of  index.js and one message is logged whenever a message is added on the web page.

Did you perhaps use the example as starter code and left in lines 11-13 of index.js? If not, could you check the database and confirm that only 1 record is created when the 2 log messages are displayed?

Lemme know.

(2) Sync'ing data between the server and client would be a package in its own right.

I think the approach Meteor takes (I've just dabbled) is the client subscribes to selected records in a db (using a query syntax?) by informing the server. The server, when it makes a change to the db, publishes any changes affecting subscriptions to the related clients. The client would be responsible to update its own db with the change, and only here is where Redux would come in.

An application may have a limited number of possible subscriptions, in which case the client identifies the specific subscription. Getting a bit more complicated, the subscription may include some params, e.g. dept='01'. At the other end of the spectrum, a client may send a flexible query identifying the records.

On initial subscription the client could get all the initial records and place them in a db in the Redux store. If the client changed a record, it would wait for the subscription to send it the changed record. (Else it could make a fast 'optimistic' update in return for more complexity.) Of course it gets updates from others.

**Comment by mishoboss** [comment]
> (1) I uncommented the messages.on code in example/client/feathers/index.js:15-25. Its functionally identical to your code above.

I think maybe you have a mistake here. Line 15 is this one:
`export const services = reduxifyServices(app, ['users', 'messages']);`

Can I execute some redux actions on server events like "created", "deleted", etc.? For example on message create to call `services.pages.create(data)` and this to store a new record in redux only, without send stuff to socket.io?

**Comment by eddyystop** [comment]
(1) That should be line 15 in example/client/index.js

(2) Yes. You can do whatever you want with the data once you get an event notification.

**Comment by mishoboss** [comment]
> (2) Yes. You can do whatever you want with the data once you get an event notification.

Are there some auto generated actions to help me do that? Or all actions send data to socket.io?

**Comment by eddyystop** [comment]
`feathers-reduxify-services` only provides the event interface. Any actionCreators or reducers would be specific to the local db you would keep in the store, and that's beyound the scope of this package.

On the other hand, these are straight forward to code. The actionCreators would dispatch an action with say `{ type: 'EVENTS_PAGES', payload: { event: 'created', data }}`. The reducer would `switch (action.payload.event)` and use `data._id` to modify the store.

The crux would be having the server notify only on what's needed by every client.

**Comment by eddyystop** [comment]
This issue was kept open for informator purposes. I think it can be closed now.
