### ISSUE TITLE
Work with REST 

### ISSUE THREAD

**Issue by mmahalwy** [eddyystop/feathers-reduxify-services#6]
Is there a way to make this work with the REST routes? In parallel I mean, with socket

**Comment by marshallswain** [comment]
If this is using the Feathers Client, then it's limited to only one transport.  You'd have to use either feathers-socketio or feathers-rest.

**Comment by eddyystop** [comment]
I don't see much of a point in having one part of a client app run via sockets, and another part run via REST, as websockets perform better than REST. Any Feathers app has to choose to go one way or the other.

You can fork the repo and replace all the service calls with fetch axios or superagent calls, those would be REST.

**Comment by mmahalwy** [comment]
Thanks guys!
